### PR TITLE
Collapse long env var values

### PR DESCRIPTION
**Pull request by spadgett**
kubernetes_describer_example

### CODE REVIEW

**Comment by spadgett** [comment]
@liggitt please review

**Comment by liggitt** [comment]
can you remove the whitespace from _collapse-long-text.html, so that copying/pasting an ellided envvar value works after you expand it?

**Comment by spadgett** [comment]
@liggitt Is this an issue? We're not using `pre` tags.

**Comment by liggitt** [comment]
if the value gets chopped, you'd have visible whitespace and copy/paste would include whitespace

**Comment by spadgett** [comment]
@liggitt sorry, still confused. I don't see any extra whitespace once we reveal it.

```
  <span style="display: none;" class="reveal-contents">{{value}}</span>
```

kubernetes_describer_example

There is an issue with copy and pasting a value that had newlines, which become spaces.

**Comment by liggitt** [comment]
nm, I thought we chopped the value into two elements.. I see we elide in the first and swap for a full one

**Pull request merged**
