### PR TITLE
Fix dependency injection of directives

### PR DESCRIPTION
**Pull request by stefwalter**
Otherwise this breaks when we minify.

### CODE REVIEW

**Comment by liggitt** [comment]
this looks fine, can you update the dist.js file in the commit as well (run `grunt build`)

**Comment by stefwalter** [comment]
> this looks fine, can you update the dist.js file in the commit as well (run grunt build)

Done. Also added a second commit for another directive that is broken when minified.

**Comment by liggitt** [comment]
Thanks. By the way, some minifiers will do angular-safe minification... might save you some grief

**Comment by stefwalter** [comment]
Perhaps. But really, bower components that are not minifier safe should distribute their own minified files.

At the end of the day, implicit dependency injection is just a bad idea. `"use strict"` exists for the same reason: the initially lax javascript behaviors were also a bad idea.

**Comment by liggitt** [comment]
Agree, thanks for the PR. Created https://github.com/kubernetes-ui/object-describer/releases/tag/v0.0.15 with this fix.

**Pull request merged**
